# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
     pip install wheel
- script: |
     pip install twine
- script: |
     python setup.py bdist_wheel
- task: TwineAuthenticate@1
  displayName: 'Twine Authenticate'
  inputs:
    artifactFeed: CDT%20Dashboard%20Efforts/snowFlakePublishPackage
- script: |
     python -m twine upload -r feedName --config-file $(PYPIRC_PATH) dist/*.whl